FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY ./requirements.txt . 

RUN pip3 install -r requirements.txt

COPY ./analysis_data.py .

CMD ["analysis_data.lambda_handler"]

